openapi: 3.0.3
info:
  title: サンプルAPI
  version: 1.0.0
servers:
  - url: 'http://localhost:4010'
    description: API server
paths:
  /healthcheck:
    post:
      tags:
        - healthcheck
      description: ヘルスチェック
      operationId: healthcheck
      requestBody:
        description: ping
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ping'
      responses:
        '200':
          $ref: '#/components/responses/ResHealthcheck'
  '/users/{userId}/murmurs/':
    get:
      tags:
        - murmurs
      description: 自分のつぶやきとフォローしているつぶやき一覧を取得する。
      operationId: getMurmurs
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          $ref: '#/components/responses/ResGetMurmurs'
    post:
      tags:
        - murmurs
      description: 自分のつぶやきを登録する。
      operationId: createMurmur
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        $ref: '#/components/requestBodies/ReqCreateMurmur'
      responses:
        '201':
          description: Created
components:
  schemas:
    Ping:
      type: object
      properties:
        ping:
          type: boolean
      required:
        - ping
    Pong:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    Murmur:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        postUserId:
          type: integer
          format: int64
        postUserName:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
      required:
        - id
        - text
        - postUserId
        - postUserName
        - createdAt
        - updatedAt
  requestBodies:
    ReqCreateMurmur:
      description: createMurmur
      content:
        application/json:
          schema:
            type: object
            properties:
              text:
                type: string
  responses:
    ResHealthcheck:
      description: pong
      content:
        application/json:
          schema:
            type: object
            items:
              $ref: '#/components/schemas/Pong'
    ResGetMurmurs:
      description: getMurmursResponse
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Murmur'
            example:
              - id: 1
                text: つぶやき7
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:07:00'
                updatedAt: '2021-07-11 12:07:00'
              - id: 1
                text: つぶやき6
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:06:00'
                updatedAt: '2021-07-11 12:06:00'
              - id: 1
                text: つぶやき5
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:05:00'
                updatedAt: '2021-07-11 12:05:00'
              - id: 1
                text: つぶやき4
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:04:00'
                updatedAt: '2021-07-11 12:04:00'
              - id: 1
                text: つぶやき3
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:03:00'
                updatedAt: '2021-07-11 12:03:00'
              - id: 1
                text: つぶやき2
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:02:00'
                updatedAt: '2021-07-11 12:02:00'
              - id: 1
                text: つぶやき1
                postUserId: 1
                postUserName: test taro
                createdAt: '2021-07-11 12:01:00'
                updatedAt: '2021-07-11 12:01:00'
